// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lagsslyarkscslutfery.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZ3NzbHlhcmtzY3NsdXRmZXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDY4NDEsImV4cCI6MjA2NjE4Mjg0MX0.vCsJAWcw1CvF-Q6sh_BdSrwhAMVG1c1VOS0g7rDk9r0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);